name: CI

on: [push, pull_request]

env: 
  REACT_APP_API_URL: http://localhost:4000

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        build: npm run build
        start: npm start
        wait-on: 'http://localhost:3000'
